---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: jb-http-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://infisical-superapp.squirrel-regulus.ts.net/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: jb-http-activity
        envSlug: prod
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: jb-http-secrets
      secretNamespace: jb-http-activity
      creationPolicy: Orphan
      template:
        includeAllSecrets: true
